language: cpp

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GCC_VER="9"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
            - doxygen
      after_script:
        - bash <(curl -s https://codecov.io/bash) -x /usr/bin/gcov-${GCC_VER}

#    - os: linux
#      dist: bionic
#      compiler: clang
#      addons:
#        apt:
#          packages:
#            - doxygen
#
#    - os: osx
#      compiler: gcc
#      osx_image: xcode11.2    # includes gcc-9 by default
#      env:
#        - GCC_VER="9"
#        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
#
#    - os: osx
#      compiler: clang
#      osx_image: xcode11.2

script:
  - mkdir build
  - cd build
  - cmake -D ENABLE_COVERAGE:BOOL=TRUE ../
  - cmake --build . -- -j2
  - ctest -j2
